theme: minimal-mistakes-jekyll
title: 'Jimmy Issa'
description: Graduate student @ Rob Ness & Alex Nguyen Ba labs, University of Toronto Mississauga
github:
  is_project_page: false   <! -- allows title in config file to override title of repository name -->
plugins:
  - jekyll-include-cache
